name: sams
description: Student Academic Management System

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  provider: ^6.1.1
  intl: ^0.19.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  pdf: ^3.12.0
  printing: ^5.14.3
  table_calendar: ^3.1.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_university.jpg
    - assets/logo_umpsa.png
