// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyq14BmAywyOEkU17MQPc8qZgXf6kCtOs',
    appId: '1:597704239021:web:68dc0e4bf48d338f0fa324',
    messagingSenderId: '597704239021',
    projectId: 'sams-project-2026',
    authDomain: 'sams-project-2026.firebaseapp.com',
    storageBucket: 'sams-project-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3fKay5M6MUBPJI_EeAWI0S8AUzb5RixQ',
    appId: '1:597704239021:android:10cbc541e19c31900fa324',
    messagingSenderId: '597704239021',
    projectId: 'sams-project-2026',
    storageBucket: 'sams-project-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIW3yOPkPVGYzzp39zYm4x4juxueNuigk',
    appId: '1:597704239021:ios:607cc41e6e930a200fa324',
    messagingSenderId: '597704239021',
    projectId: 'sams-project-2026',
    storageBucket: 'sams-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.facultyRegistrar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIW3yOPkPVGYzzp39zYm4x4juxueNuigk',
    appId: '1:597704239021:ios:607cc41e6e930a200fa324',
    messagingSenderId: '597704239021',
    projectId: 'sams-project-2026',
    storageBucket: 'sams-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.facultyRegistrar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyq14BmAywyOEkU17MQPc8qZgXf6kCtOs',
    appId: '1:597704239021:web:ef3a4d63bc58ff280fa324',
    messagingSenderId: '597704239021',
    projectId: 'sams-project-2026',
    authDomain: 'sams-project-2026.firebaseapp.com',
    storageBucket: 'sams-project-2026.firebasestorage.app',
  );
}
